---
- name: "Create directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unzip artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: "Start app"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
