---
- name: "Create directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unzip artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Install node"
  shell: |
    cd ~/backend-app
    chown -R $(whoami):root $(npm root -g)
    npm i
    npm -v
    
- name: "Start app"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
